### ISSUE TITLE
Cant find yolo model

### ISSUE THREAD

**Issue by Sicos1977** [BobLd/YOLOv4MLNet#16]
I clicked the link https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov4 but it is pointing to nowhere.

Any idea where to find it otherwise?

**Comment by Sicos1977** [comment]
Seems that they changed to github repro ... it is now overhere --> https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/yolov4

**Comment by BobLd** [comment]
Thanks @Sicos1977, I'll update the readme shortly

**Comment by Sicos1977** [comment]
@BobLd : I was looking into Yolo to use it to detect id cards, passports and driving licences. I just need to know if it is in the picture. I don't need to extract any information from it. I tried Yolo but that one does not seem to work. It detects all kinds of things but not the things I need. Do you know any model that I can use for this? Any help would be nice because I'm very new regarding detecting objects with AI.

**Comment by BobLd** [comment]
@Sicos1977 in order to detect the specific objects you are interested in, you will have to train your own model I think. You will need to find or build your own dataset with the objects you want to detect.

Then, most of the time you will need python to train your own model.

You might want to look into this link to train using VS 2022 https://devblogs.microsoft.com/dotnet/object-detection-ml-dotnet-model-builder/

**Comment by Sicos1977** [comment]
I already did see that blog post. The problem I have is finding a lot id card examples. I tried searching on Google but most of the images there are all the same.. Thanks anyway.
